# Generated by Django 6.0.2 on 2026-02-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Commercial', 'Commercial'), ('Plot', 'Plot')], max_length=50)),
                ('listing_type', models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=20)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('area', models.IntegerField(help_text='Area in sqft')),
                ('featured_image', models.ImageField(upload_to='properties/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
