# Generated by Django 6.0.2 on 2026-02-27 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
    ]
