# Generated by Django 4.2.16 on 2026-03-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_visitbooking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitbooking',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
